[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
indoc = "2"
egui-modal = "0.2.1"
tinyfiledialogs = "3.0"